//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRUP_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.ExamClassroom = new HashSet<ExamClassroom>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool HasComputers { get; set; }
        public int Places { get; set; }
    
        public virtual ICollection<ExamClassroom> ExamClassroom { get; set; }
    }
}
