//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRUP_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.ExamClassroom = new HashSet<ExamClassroom>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Creator { get; set; }
        public string Speciality { get; set; }
        public bool ComputerNeeded { get; set; }
        public bool Surveillant { get; set; }
        public int ExpectedStudents { get; set; }
        public int ResultIsDecimal { get; set; }
        public Nullable<int> QuarterId { get; set; }
        public int MinutesDuration { get; set; }
    
        public virtual ICollection<ExamClassroom> ExamClassroom { get; set; }
    }
}
