//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRUP_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HUInspectorEntities : DbContext
    {
        public HUInspectorEntities()
            : base("name=HUInspectorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classroom> Classroom { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<ExamClassroom> ExamClassroom { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
